services:
  nginx:
    image: public.ecr.aws/docker/library/nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ../frontend/:/home/ishocon/webapp/public:ro
    ports:
      - "8080:80"
    depends_on:
      - webapp
  payment_app:
    build:
      context: ../payment_app/
      dockerfile: ../development/payment_app/Dockerfile
    image: payment-app
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl -f http://localhost:8081/healthz || exit 1"
      start_period: 5s
  db:
    image: public.ecr.aws/docker/library/mysql:8
    environment:
      ENV: local-dev
      MYSQL_DATABASE: ishocon3
      MYSQL_ROOT_PASSWORD: ishocon
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ../webapp/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ishocon -pishocon
      start_period: 60s
