services:
  nginx:
    image: public.ecr.aws/docker/library/nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ../frontend/:/home/ishocon/webapp/public:ro
    ports:
      - "8080:80"
    depends_on:
      - webapp
<<<<<<< HEAD:development/docker-compose.base.yml
||||||| parent of a95f53f (Redisをつかって空席を管理 score=2570 total_sales=257000 total_refunds=0 net_revenue=257000 total_tickets=143 ticket_phase=5/5 sales_phase=5/7):development/compose-python.yml
  webapp:
    build:
      context: ../webapp/python
      dockerfile: ../../development/dockerfiles/Dockerfile.python
    image: webapp-python
    expose:
      - 8080
    volumes:
      - ../webapp/sql:/home/ishocon/webapp/sql
    working_dir: /home/ishocon/webapp/python
    depends_on:
      db:
        condition: service_healthy
      # payment_app:
      #   condition: service_healthy
    environment:
      ISHOCON_DB_HOST: db
      ISHOCON_DB_OPTIONS: "--ssl-verify-server-cert=FALSE"
      ISHOCON_PAYMENT_HOST: payment_app
      ISHOCON_PAYMENT_PORT: 8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
=======
  webapp:
    build:
      context: ../webapp/python
      dockerfile: ../../development/dockerfiles/Dockerfile.python
    image: webapp-python
    expose:
      - 8080
    ports:
      - "8082:8080"
    volumes:
      - ../webapp/sql:/home/ishocon/webapp/sql
    working_dir: /home/ishocon/webapp/python
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      # payment_app:
      #   condition: service_healthy
    environment:
      ISHOCON_DB_HOST: db
      ISHOCON_DB_OPTIONS: "--ssl-verify-server-cert=FALSE"
      ISHOCON_PAYMENT_HOST: payment_app
      ISHOCON_PAYMENT_PORT: 8080
      ISHOCON_REDIS_HOST: redis
      ISHOCON_REDIS_PORT: 6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
>>>>>>> a95f53f (Redisをつかって空席を管理 score=2570 total_sales=257000 total_refunds=0 net_revenue=257000 total_tickets=143 ticket_phase=5/5 sales_phase=5/7):development/compose-python.yml
  payment_app:
    build:
      context: ../payment_app/
      dockerfile: ../development/payment_app/Dockerfile
    image: payment-app
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl -f http://localhost:8081/healthz || exit 1"
      start_period: 5s
  db:
    image: public.ecr.aws/docker/library/mysql:8
    environment:
      ENV: local-dev
      MYSQL_DATABASE: ishocon3
      MYSQL_ROOT_PASSWORD: ishocon
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ../webapp/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ishocon -pishocon
      start_period: 60s
  redis:
    image: public.ecr.aws/docker/library/redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
